### PR TITLE
Add sort capability

### PR DESCRIPTION
**Pull request by danipatko**
Enable sorting for the hash data structure, for number, string and boolean field types.
Syntax:
```ts
const sorted = await repository.search().sortBy('field').returnAll();
```
Also added `min` and `max` functions mentioned in #10 
```ts
const biggest = await search.min('numberField');    // or await search.returnMin('numberField');
const smallest = await search.max('numberField');  // or await search.returnMax('numberField');
```

### CODE REVIEW

**Comment by guyroyse** [comment]
A quick glance and this looks pretty solid. Thanks for an awesome contribution! I'll go over it more thoroughly this week, we can go through the review cycle, and we'll hopefully get it merged. Thanks!

**Comment by guyroyse** [comment]
Want to let you know that I haven't forgotten about this. Just competing priorities on my time. It shall be merged at some point!

**Comment by guyroyse** [comment]
Merged this to a branch and will do the work to integrate it with the changes that I have wrought since you create this request. Thanks so much for your contribution!

**Comment by guyroyse** [comment]
Hey @danipatko, are you cool with me giving you a shout out in the Redis Blog to thank you for contributing this to Redis OM?

**Comment by danipatko** [comment]
Yeah, I would gladly accept that, thank you.

**Pull request merged**
