### PR TITLE
Old code using string for Schema definitions doesn't work

### PR DESCRIPTION
**Pull request by spdrman**
This was from using the library in a Typescript app. I kept getting an error because 'album' couldn't be used in place of ctor: EntityConstructor<TEntity>

### CODE REVIEW

**Comment by guyroyse** [comment]
The README in main branch is for Redis OM 0.4.0 *beta* as noted at the top of the README and thus the code examples are also for that version. For the current non-beta version, see the [README at NPM](https://www.npmjs.com/package/redis-om/v/0.3.6).

**Comment by guyroyse** [comment]
Would really like it if you'd try out the beta though!

**Comment by spdrman** [comment]
Hahaha I got confused by the "Beta" next to code in npm... unfortunately it looks like npm is trying out a Beta feature of their own, and it is unfortunately attached to Code, which made me believe that the nom contained the Beta version of the code hahaha:

image

**Comment by guyroyse** [comment]
It ain't just you. It actually confused me a couple of times when I saw it as well. Kept trying to click on it to get to the Beta version of Redis OM!

**Comment by spdrman** [comment]
> It ain't just you. It actually confused me a couple of times when I saw it as well. Kept trying to click on it to get to the Beta version of Redis OM!

I switched to beta. Definitely an improvement. Will report issues. Thanks for manning this post. Appreciate ya!

**Pull request closed without merging**
